- docker-swarm-ha/README.md
- docker-swarm-ha/Vagrantfile
- docker-swarm-ha/config.json.erb
- docker-swarm-ha/consul.conf
- docker-swarm-ha/consul.sh
- docker-swarm-ha/server.json
- docker-swarm-ha/servers.yml
Add learning environment for Docker Swarm with multiple managers.
> Docker Swarm Multiple Managers

- README.md
> updating readme with a references section to other useful projects

- photon-ansible/Vagrantfile
- photon-ansible/ansible.cfg
- photon-ansible/docker-tcp.socket
- photon-ansible/docker.service
- photon-ansible/docker.socket
- photon-ansible/machines.yml
- photon-ansible/provision.yml
Add new learning environment for Photon and Ansible. Add Vagrantfile, supporting files, Ansible playbook, and Ansible configuration file.
> Add new learning environment for Photon and Ansible

- kvm/README.md
- kvm/Vagrantfile
- kvm/ansible.cfg
- kvm/machines.yml
- kvm/provision.yml
Add Vagrantfile and supporting files to create a learning environment for KVM and Libvirt.
> Add learning environment for KVM

- consul-ansible/README.md
- consul-ansible/Vagrantfile
- consul-ansible/ansible.cfg
- consul-ansible/config.json.j2
- consul-ansible/consul.conf
- consul-ansible/hosts
- consul-ansible/machines.yml
- consul-ansible/provision.yml
Create new learning environment for Consul that uses Ansible for provisioning instead of a shell script.
> Create environment for Consul using Ansible

- vagrant-json/README.md
- vagrant-json/Vagrantfile
- vagrant-json/machines.json
Add JSON data file. Add modified Vagrantfile to read external JSON data file.
> Add initial set of files for using JSON data file with Vagrant

- docker-swarm/Vagrantfile
- docker-swarm/consul.sh
- docker-swarm/server.json.erb
Add ERB template for Consul configuration. Modify Vagrantfile to use ERB template. Update provisioning shell script.
> Fix Consul cluster setup for Docker Swarm cluster

- docker-macvlan/README.md
- docker-macvlan/Vagrantfile
- docker-macvlan/machines.yml
Create a new learning environment for using Docker with macvlan interfaces.
> Create learning environment for Docker with macvlan interfaces

- docker-ipvlan/README.md
- docker-ipvlan/Vagrantfile
- docker-ipvlan/machines.yml
Add machines.yml, Vagrantfile, and README.md for using Docker containers with ipvlan interfaces.
> Add learning environment for Docker with ipvlan interfaces

- vagrant-aws/README.md
- vagrant-aws/Vagrantfile
- vagrant-aws/instances.yml
Add Vagrantfile, external YAML data file, and README.md for using Vagrant to spin up an instance on AWS.
> Add files for using Vagrant with AWS

- consul-ansible/Vagrantfile
- consul/Vagrantfile
- coreos-cloudinit-toolbox/Vagrantfile
- debian-generic/Vagrantfile
- docker-ipvlan/Vagrantfile
- docker-macvlan/Vagrantfile
- docker-swarm-ha/Vagrantfile
- kvm-macvtap/Vagrantfile
- kvm/Vagrantfile
- lxc/Vagrantfile
- lxd-ansible/Vagrantfile
- ovs-geneve/Vagrantfile
- photon-ansible/Vagrantfile
- photon-cloudinit/Vagrantfile
- ssh-bastion/Vagrantfile
- ubuntu-generic/Vagrantfile
- vagrant-json/Vagrantfile
Remove all references to AppCatalyst from all Vagrantfiles. Start ensuring that all Vagrantfiles include references to VirtualBox.
> Remove all references to AppCatalyst

- docker-ipvlan/README.md
- docker-ipvlan/Vagrantfile
- docker-ipvlan/docker-provision.sh
- docker-ipvlan/machines.yml
- docker-ipvlan/remote-provision.sh
Commit updated Vagrantfile, YAML data file, shell provisioning scripts, and updated README.md.
> Commit new version of Docker+IPVLAN environment

- docker-ipvlan-l3/README.md
- docker-ipvlan-l3/Vagrantfile
- docker-ipvlan-l3/docker-01-setup.sh
- docker-ipvlan-l3/docker-02-setup.sh
- docker-ipvlan-l3/machines.yml
Add Vagrantfile and external YAML data file for IPVLAN L3 environment with Docker. Add shell scripts for configuring Docker host VMs. Update README.md for IPVLAN L3 instead of IPVLAN L2.
> Commit files for IPVLAN L3 environment with Docker

- vagrant-multi-platform/README.md
- vagrant-multi-platform/Vagrantfile
- vagrant-multi-platform/vbrc
- vagrant-multi-platform/vmwrc
Switch to using provider override to support multi-platform environments.
> Switch to provider override

- ipvs-docker/README.md
- ipvs-docker/Vagrantfile
- ipvs-docker/machines.yml
- ipvs-docker/provision.sh
Add a learning environment for working with IPVS to load balance connections to Docker containers.
> Add files for using IPVS with Docker

- terraform-aws/.gitignore
- terraform-aws/README.md
- terraform-aws/simple-ec2/data.tf
- terraform-aws/simple-ec2/main.tf
- terraform-aws/simple-ec2/provider.tf
- terraform-aws/simple-ec2/vars.tf
Add learning environments that provide examples on how to use Terraform with AWS.
> Add Terraform-AWS learning environments

- ansible-aws/README.md
- ansible-aws/ansible.cfg
- ansible-aws/create.yml
- ansible-aws/delete.yml
- ansible-aws/ec2.ini
- ansible-aws/ec2.py
- ansible-aws/inventory
Add a learning environment to demonstrate how to use Ansible to manage AWS infrastructure. Environment needs to include examples of creating infrastructure as well as deleting infrastructure.
> Commit learning environment for using Ansible with AWS

- ovn-kvm/README.md
- ovn-kvm/Vagrantfile
- ovn-kvm/ansible.cfg
- ovn-kvm/final-setup.sh
- ovn-kvm/machines.yml
- ovn-kvm/net-setup.sh
- ovn-kvm/ovn-setup.sh.j2
- ovn-kvm/ovs.xml
- ovn-kvm/provision.yml
- ovn-kvm/vm-setup.sh
Add a learning environment that would allow users to use KVM-based VMs with OVN.
> Add learning environment for KVM+OVN

- README.md
Update README.md to reflect that OVN directory is ready for use
Signed-off-by: Scott S. Lowe <scott.lowe@scottlowe.org>
> Update README.md for OVN

- centos-atomic/docker-tcp/Vagrantfile
- centos-atomic/docker-tcp/docker-socket.conf
- centos-atomic/docker-tcp/docker-tcp.socket
- centos-atomic/docker-tcp/docker.socket
- centos-atomic/docker-tcp/machines.yml
- centos-atomic/docker-tcp/setup.sh
Add a learning environment for customizing Docker Engine on a CentOS Atomic host.
> Add learning environment for customizing Docker on CentOS Atomic Host

- centos-atomic/docker-tcp-ansible/Vagrantfile
- centos-atomic/docker-tcp-ansible/docker-socket.conf
- centos-atomic/docker-tcp-ansible/docker-tcp.socket
- centos-atomic/docker-tcp-ansible/docker.socket
- centos-atomic/docker-tcp-ansible/machines.yml
- centos-atomic/docker-tcp-ansible/provision.yml
Add Vagrant environment that demonstrates using Ansible to customize Docker Engine on Atomic Host.
> Add environment for using Ansible to customize Atomic Host

- ansible/src-dst-list/Vagrantfile
- ansible/src-dst-list/docker-socket.conf
- ansible/src-dst-list/docker-tcp.socket
- ansible/src-dst-list/docker.socket
- ansible/src-dst-list/machines.yml
- ansible/src-dst-list/provision.yml
I'd like to figure out how to use more complex lists to simplify the use of "with_items" in Ansible playbooks. This will help me consolidate certain task blocks and make playbooks easier to read/follow.
> Add environment for Ansible "with_items" testing

- docker/coreos-swarm-mode/README.md
- docker/coreos-swarm-mode/Vagrantfile
- docker/coreos-swarm-mode/machines.yml
Add a learning environment to simplify learning, experimenting, or working with Docker in Swarm Mode on CoreOS.
> Add learning environment for Docker Swarm Mode on CoreOS

- .gitignore
- docker/swarm-consul/consul.sh
- docker/swarm-ha/README.md
- docker/swarm-ha/consul.sh
changed from 0.7.0 to latest consul version
added temporary consul config files to .gitignore
> changed from 0.7.0 to latest consul version

- terraform/aws/README.md
- terraform/aws/simple-module/main.tf
- terraform/aws/simple-module/modules/vpc/main.tf
- terraform/aws/simple-module/modules/vpc/output.tf
- terraform/aws/simple-module/modules/vpc/variables.tf
- terraform/aws/simple-module/provider.tf
- terraform/aws/simple-module/variables.tf
Add an example learning environment that shows how to use Terraform modules for more reusable code
> Add an example of using Terraform modules

- terraform/aws/bastion-aws/provider.tf
- terraform/aws/bastion-aws/variables.tf
Clean up Terraform+AWS SSH bastion environment. This is part of #80.
Signed-off-by: Scott Lowe <scott.lowe@scottlowe.org>
> Clean up SSH bastion environment

- terraform/aws/asg-elb/README.md
- terraform/aws/asg-elb/data.tf
- terraform/aws/asg-elb/main.tf
- terraform/aws/asg-elb/output.tf
- terraform/aws/asg-elb/provider.tf
- terraform/aws/asg-elb/variables.tf
Add Terraform configurations for creating an Auto Scaling Group and an Elastic Load Balancer.
> Add a learning environment for ASG-ELB using Terraform

- docker/ubuntu-swarm-mode/README.md
- docker/ubuntu-swarm-mode/Vagrantfile
- docker/ubuntu-swarm-mode/ansible.cfg
- docker/ubuntu-swarm-mode/create-swarm.yml
- docker/ubuntu-swarm-mode/destroy-swarm.yml
- docker/ubuntu-swarm-mode/machines.yml
- docker/ubuntu-swarm-mode/provision.yml
This new learning environment would provision a set of local VMs using Vagrant, and then use Ansible to provision Docker and create a Swarm mode cluster.
Once finished and merged, this learning environment might serve as the basis for other learning environments that also depend on a Swarm mode cluster.
> Add learning environment for running a local Docker Swarm mode cluster

- traefik/tf-ans-swarm/README.md
- traefik/tf-ans-swarm/ansible.cfg
- traefik/tf-ans-swarm/compute.tf
- traefik/tf-ans-swarm/create-swarm.yml
- traefik/tf-ans-swarm/data.tf
- traefik/tf-ans-swarm/destroy-swarm.yml
- traefik/tf-ans-swarm/ec2.ini
- traefik/tf-ans-swarm/ec2.py
- traefik/tf-ans-swarm/networking.tf
- traefik/tf-ans-swarm/output.tf
- traefik/tf-ans-swarm/provider.tf
- traefik/tf-ans-swarm/security.tf
- traefik/tf-ans-swarm/variables.tf
Add a learning environment that leverages Terraform for infrastructure creation and Ansible to configure instances into a Docker Swarm mode cluster.
> Add a Traefik learning environment leveraging Ubuntu on AWS

- ansible/bootstrap/ansible.cfg
- ansible/bootstrap/bootstrap.yml
- ansible/bootstrap/compute.tf
- ansible/bootstrap/datasources.tf
- ansible/bootstrap/ec2.ini
- ansible/bootstrap/ec2.py
- ansible/bootstrap/provider.tf
- ansible/bootstrap/variables.tf
This PR contains files for showing how to bootstrap an Ubuntu 16.04 instance for use with Ansible.
Closes #95.
> Add files to show how to bootstrap Ubuntu 16.04 for Ansible

- terraform/aws/ic-module/README.md
- terraform/aws/ic-module/data.tf
- terraform/aws/ic-module/main.tf
- terraform/aws/ic-module/modules/instance-cluster/main.tf
- terraform/aws/ic-module/modules/instance-cluster/output.tf
- terraform/aws/ic-module/modules/instance-cluster/variables.tf
- terraform/aws/ic-module/modules/vpc/data.tf
- terraform/aws/ic-module/modules/vpc/main.tf
- terraform/aws/ic-module/modules/vpc/output.tf
- terraform/aws/ic-module/modules/vpc/variables.tf
- terraform/aws/ic-module/provider.tf
- terraform/aws/ic-module/variables.tf
This environment not only shows how to use multiple modules, but also shows how to launch groups of instances across subnets/AZs.
> Add an environment showing how to use multiple Terraform modules

- vagrant/azure/README.md
- vagrant/azure/Vagrantfile
- vagrant/azure/instances.yml
Add files (Vagrantfile and YAML data file) for using Vagrant with Azure
> Add files for using Vagrant with Azure

- ansible/pulumi-env/roles/pulumi-env/vars/main.yml
This PR increments the Pulumi version to 0.17.16.
> Update Pulumi version

- aws/postman-aws-api/describe-azs-test.js
- aws/postman-aws-api/describe-images-test.js
- aws/postman-aws-api/describe-key-pairs-test.js
- aws/postman-aws-api/describe-subnets-test.js
- aws/postman-aws-api/describe-vpcs-test.js
This PR contains commits that will add some sample JavaScript tests for use with Postman API requests.
> Add sample JavaScript tests

- ansible/README.md
- ansible/golang-role/README.md
- ansible/golang-role/tasks/main.yml
- ansible/golang-role/vars/main.yml
This PR adds a simple Ansible role to install Golang on a Linux system.
> Add a simple Golang role

- ansible/wireguard/README.md
- ansible/wireguard/ansible.cfg
- ansible/wireguard/wireguard.yaml
This PR adds a simple Wireguard playbook that performs a basic Wireguard installation on Ubuntu.
> Add simple Wireguard playbook

- golang/README.md
- golang/generate-ssh-key/README.md
- golang/generate-ssh-key/go.mod
- golang/generate-ssh-key/main.go
Add Golang code example for generating SSH key along with associated documentation.
> Add Golang code for generating SSH key

- pulumi/README.md
- pulumi/eks-from-scratch/Pulumi.yaml
- pulumi/eks-from-scratch/README.md
- pulumi/eks-from-scratch/go.mod
- pulumi/eks-from-scratch/iam.go
- pulumi/eks-from-scratch/main.go
- pulumi/eks-from-scratch/vpc.go
This PR adds a Go example to show building EKS cluster from scratch with Pulumi. "From scratch" means that no high-level component resources (such as AWSX or EKS) are used.
> Add example of building EKS from scratch

- flatcar/README.md
- flatcar/flatcar-pulumi-aws/Pulumi.yaml
- flatcar/flatcar-pulumi-aws/README.md
- flatcar/flatcar-pulumi-aws/go.mod
- flatcar/flatcar-pulumi-aws/main.go
Add a Pulumi program for standing up Flatcar Linux on AWS EC2
> Add Flatcar Linux resources

- ubuntu/ubuntu-pulumi-aws/Pulumi.yaml
- ubuntu/ubuntu-pulumi-aws/README.md
- ubuntu/ubuntu-pulumi-aws/go.mod
- ubuntu/ubuntu-pulumi-aws/main.go
Add a Pulumi program written in Go to stand up an Ubuntu EC2 instance
> Add Ubuntu instance Pulumi program

- debian/README.md
- debian/debian-pulumi-azure/Pulumi.yaml
- debian/debian-pulumi-azure/README.md
- debian/debian-pulumi-azure/go.mod
- debian/debian-pulumi-azure/main.go
This PR adds a Pulumi program (written in Go) for running Debian on Azure
> Add program for Debian on Azure

- coreos/fcos-pulumi-aws/Pulumi.yaml
- coreos/fcos-pulumi-aws/README.md
- coreos/fcos-pulumi-aws/go.mod
- coreos/fcos-pulumi-aws/main.go
This PR adds a Pulumi program, written in Go, to stand up Fedora CoreOS on AWS.
> Add Fedora CoreOS program

- docker/docker-ssh-pulumi/Pulumi.yaml
- docker/docker-ssh-pulumi/README.md
- docker/docker-ssh-pulumi/go.mod
- docker/docker-ssh-pulumi/main.go
This PR adds a Go program illustrating use of an SSH-based Docker provider.
> Add SSH-based Docker provider example

- azure/vhd-storage-pulumi/Pulumi.yaml
- azure/vhd-storage-pulumi/go.mod
- azure/vhd-storage-pulumi/main.go
This PR adds a Pulumi program (written in Go) to create a storage account and a storage container, ostensibly for uploading a custom VHD as a VM image.
> Add a storage program

- aws/README.md
- aws/nat-instance-pulumi/Pulumi.yaml
- aws/nat-instance-pulumi/README.md
- aws/nat-instance-pulumi/go.mod
- aws/nat-instance-pulumi/main.go
- aws/nat-instance-pulumi/nat.go
- aws/nat-instance-pulumi/vpc.go
This PR adds a program to illustrate the use of Pulumi to create and configure a NAT instance instead of a more costly Managed NAT Gateway.
Closes #161.
> [WIP] Add a program illustrating the use of a NAT instance

- pulumi/aws-k8s-infra/go.mod
- pulumi/aws-k8s-infra/main.go
This PR changes the code to use a NAT instance instead of a NAT gateway.
It also updates the AWS provider to v6.
> Switch to NAT instance instead of NAT gateway
