scottslowe/learning-tools

- vagrant-docker/host/Vagrantfile
Kill SSH connection to force re-connecting and updating group membership in order to correct Docker daemon error
> Fix Docker error related to group membership

- .gitignore
- terraform/tf-example/main.tf
- terraform/tf-example/output.tf
- terraform/tf-example/provider.tf
Use openstack_networking_floatingip_v2 instead of
openstack_compute_floatingip_v2 to make use of
Neutron floating IPs in the Terraform example.
Also update the .gitignore to ignore the terraform
DB which is generated.
Signed-off-by: Kyle Mestery <mestery@mestery.com>
> terraform: Use Neutron floating IPs

- docker-swarm/README.md
Updating the README.md for docker-swarm to move progrium/registrator to gliderlabs/registrator per https://hub.docker.com/r/progrium/registrator/
> progrium/registrator to gliderlabs/registrator

- docker-swarm-ha/Vagrantfile
- docker-swarm/Vagrantfile
- etcd-2.0/Vagrantfile
- openstack-cli/Vagrantfile
- photon-cloudinit/Vagrantfile
- photon/Vagrantfile
- rkt/Vagrantfile
- swarm-etcd2-photon/Vagrantfile
- vagrant-docker-yaml/Vagrantfile
- vagrant-docker/Vagrantfile
- vagrant-openstack-multi/Vagrantfile
- vagrant-openstack/Vagrantfile
Add Ruby code to determine full path to supporting files referenced in all Vagrantfiles. This will allow more effective use of Vagrant commands when not in the same directory as the Vagrantfile.
> Add Ruby code to all Vagrantfiles

- kvm-macvtap/README.md
- kvm-macvtap/Vagrantfile
- kvm-macvtap/ansible.cfg
- kvm-macvtap/machines.yml
- kvm-macvtap/macvtap.xml
- kvm-macvtap/noop.yml
- kvm-macvtap/provision.yml
This is an initial set of files for working with KVM and macvtap interfaces for KVM guests. The environment is not yet functional, but this is a start. Changes need to be made to the Ansible provisioning, and a way to enable promiscuous mode needs to be found.
> Add learning environment for KVM and macvtap

- lxd-ansible/provision.yml
Update Ansible playbook to use Trusty backports repository instead of custom PPA.
> Update Ansible playbook

- vagrant-docker-json/README.md
- vagrant-docker-json/Vagrantfile
- vagrant-docker-json/containers.json
- vagrant-docker-json/host/Vagrantfile
Add files for a multi-container environment using the Vagrant Docker provider and an external JSON data file. That includes a Vagrantfile, external JSON data file, host VM Vagrantfile, and README.md.
> Add files for Vagrant + Docker + JSON

- coreos-cloudinit-toolbox/README.md
- coreos-cloudinit-toolbox/Vagrantfile
- coreos-cloudinit-toolbox/machines.yml
- coreos-cloudinit-toolbox/user-data
Add Vagrantfile, machines.yml, and user-data for use with local Vagrant environment. Add README.md with instructions for using local Vagrant environment, OpenStack instances, or AWS instances.
> Add files for using cloud-init to customize CoreOS toolbox

- vagrant-multi-platform/README.md
- vagrant-multi-platform/Vagrantfile
- vagrant-multi-platform/machines.yml
- vagrant-multi-platform/vbrc
- vagrant-multi-platform/vmwrc
Add a learning/testing environment that supports the use of Vagrant on multiple platforms and with multiple virtualization providers with _no_ changes to the `Vagrantfile`.
> Add final Vagrant multi-platform environment

- ovs-multi-br/README.md
- ovs-multi-br/Vagrantfile
- ovs-multi-br/ansible.cfg
- ovs-multi-br/br0.xml
- ovs-multi-br/br1.xml
- ovs-multi-br/machines.yml
- ovs-multi-br/provision.yml
Add Libvirt XML definitions, Ansible configuration file and playbook, YAML data file, README, and Vagrantfile for an environment enabling users to easily experiment with multi-bridge OVS configurations. Instructions are not yet fully complete. Also tracking a potential bug in the openvswitch_port Ansible module used (see https://github.com/ansible/ansible-modules-extras/issues/2500).
> Add new environment for working with multiple OVS bridges

- vagrant-aws-multi/README.md
- vagrant-aws-multi/Vagrantfile
- vagrant-aws-multi/instances.yml
Add files for a learning environment that supports spinning up multiple instances on AWS via Vagrant with the `vagrant-aws` provider.
> Add new environment for using Vagrant with AWS (multiple instances)

- vagrant-aws/README.md
I'm pretty sure "OpenStack" should be "AWS."
> Fix typo in readme.md

- terraform-aws/new-vpc/data.tf
- terraform-aws/new-vpc/main.tf
- terraform-aws/new-vpc/provider.tf
- terraform-aws/new-vpc/vars.tf
Add an example Terraform configuration for launching an instance in a new VPC. This includes creating a new VPC, a new subnet, a new Internet gateway, a new route table, and a new route table association (all required when creating a new VPC).
> Add a Terraform configuration for creating a new VPC

- docker/atomic-swarm-mode/README.md
- docker/atomic-swarm-mode/Vagrantfile
- docker/atomic-swarm-mode/machines.yml
Add a Vagrant-based learning environment that will enable users to experiment with Docker Swarm Mode using CentOS Atomic Host.
> Add a learning environment for Docker Swarm Mode with CentOS Atomic Host

- terraform/aws/bastion-aws/data.tf
- terraform/aws/bastion-aws/instances.tf
- terraform/aws/bastion-aws/networking.tf
- terraform/aws/bastion-aws/output.tf
- terraform/aws/bastion-aws/provider.tf
- terraform/aws/bastion-aws/security.tf
- terraform/aws/bastion-aws/ssh.cfg
- terraform/aws/bastion-aws/vars.tf
The goal would be to provide sample Terraform configurations so that users can see how to build out an entirely new AWS environment (new VPC, new subnets, new security groups, etc.) with an SSH bastion host for secure SSH access to private instances.
> Add learning environment to show Terraform building an SSH bastion host on AWS

- terraform/aws/simple-ec2/output.tf
- terraform/aws/simple-ec2/provider.tf
- terraform/aws/simple-ec2/variables.tf
The "simple-ec2" environment needs some cleanup to make it easier for other people to use. Variables need to be moved to a `*.tfvars` file (excluded from source control) and output needs to be added.
> Clean up simple EC2 environment

- terraform/aws/new-vpc/output.tf
- terraform/aws/new-vpc/provider.tf
- terraform/aws/new-vpc/variables.tf
Clean up Terraform+AWS `new-vpc` environment to adhere to standards described in issue #80.
Signed-off-by: Scott Lowe <scott.lowe@scottlowe.org>
> Clean up environment

- CONTRIBUTING.md
Add initial contribution guidelines in the form of CONTRIBUTING.md.
Closes #84.
Signed-off-by: Scott Lowe <scott.lowe@scottlowe.org>
> Add initial contribution guidelines

- centos-atomic/docker-cloudinit/README.md
- centos-atomic/docker-cloudinit/cloud-config.yml
- centos-atomic/docker-cloudinit/launch.sh
- centos-atomic/docker-cloudinit/ssh.cfg
- terraform/aws/bastion-aws/ssh.cfg.example
Adds files to demonstrate the use of `cloud-init` on AWS to customize the Docker daemon on CentOS Atomic Host. Assumes the presence of the AWS CLI.
Closes #86.
> Add learning environment demonstrating cloud-init to customize Docker

- packer/aws-ami-ansible/README.md
- packer/aws-ami-ansible/provision.yml
- packer/aws-ami-ansible/roles/docker-ce-edge/tasks/main.yml
- packer/aws-ami-ansible/template.json
- packer/aws-ami-ansible/variables.json
Add an environment for using Packer to build an AWS AMI that is pre-provisioned with Docker CE Edge.
Addresses #77.
> Add files for building AMI with Packer

- traefik/vagrant-ansible/README.md
- traefik/vagrant-ansible/Vagrantfile
- traefik/vagrant-ansible/ansible.cfg
- traefik/vagrant-ansible/create-swarm.yml
- traefik/vagrant-ansible/destroy-swarm.yml
- traefik/vagrant-ansible/machines.yml
- traefik/vagrant-ansible/provision.yml
This learning environment (based on the `docker/ubuntu-swarm-mode` environment) will allow users to spin up a local Docker Swarm mode cluster and then deploy Traefik and other web services onto it. This will facilitate learning how Traefik (and other dynamic reverse proxies) work in microservices-based environments.
> Add learning environment for Traefik on local Docker Swarm mode cluster

- terraform/aws/vpc-all-azs/README.md
- terraform/aws/vpc-all-azs/compute.tf
- terraform/aws/vpc-all-azs/data.tf
- terraform/aws/vpc-all-azs/networking.tf
- terraform/aws/vpc-all-azs/provider.tf
- terraform/aws/vpc-all-azs/variables.tf
The purpose of this environment is to show how to determine the number of AZs within a region, then use that information to create a subnet in each region and launch an instance in each subnet.
The technique demonstrated here can be leveraged for other (more useful) purposes, such as spreading cluster members across subnets for higher availability.
> Add an environment demonstrating how to dynamically accommodate availability zones

- terraform/aws/ic-module-asg/README.md
- terraform/aws/ic-module-asg/data.tf
- terraform/aws/ic-module-asg/main.tf
- terraform/aws/ic-module-asg/modules/ic-asg/main.tf
- terraform/aws/ic-module-asg/modules/ic-asg/variables.tf
- terraform/aws/ic-module-asg/modules/vpc/data.tf
- terraform/aws/ic-module-asg/modules/vpc/main.tf
- terraform/aws/ic-module-asg/modules/vpc/output.tf
- terraform/aws/ic-module-asg/modules/vpc/variables.tf
- terraform/aws/ic-module-asg/provider.tf
- terraform/aws/ic-module-asg/variables.tf
This new environment uses Terraform modules to create a new VPC and new subnets (across all availability zones in that region), and then uses launch configurations/Auto Scaling Groups to create "instance clusters" (groups of instances used for the same purpose/role).
> Add environment leveraging Auto Scaling Groups

- fedora-atomic/26-atomic-generic/README.md
- fedora-atomic/26-atomic-generic/Vagrantfile
- fedora-atomic/26-atomic-generic/machines.yml
This environment can serve as a basis for more complex environments in the future.
> Add generic environment for Fedora 26 Atomic Host

- ansible/extract-gh-archive/README.md
- ansible/extract-gh-archive/Vagrantfile
- ansible/extract-gh-archive/machines.yml
- ansible/extract-gh-archive/provision.yml
Add Ansible+Vagrant environment to demonstrate using Ansible to download a binary release from GitHub, extract it, and copy out the relevant binary into the path. Not terribly unusual or unique, but shows a few techniques that early Ansible users may not know.
> Add environment to install GitHub binary using Ansible

- terraform/oci/data.tf
- terraform/oci/main.tf
- terraform/oci/outputs.tf
- terraform/oci/provider.tf
- terraform/oci/variables.tf
This PR adds a sample Terraform configuration that shows how to use Terraform with Oracle Cloud Infrastructure (OCI) using the OCI provider.
> Add Terraform configuration for working with Oracle Cloud

- kubernetes/kubeadm-vagrant/README.md
Proposing changes to kubeadm-vagrant instructions as per issue #120 . Have split into two commits, one for running K8s services on each VM's second NIC, and one for running the latest Calico containers. I needed both to be in place before the instructions would work (using VirtualBox on Linux).
> kubeadm-vagrant readme

- ansible/pulumi-env/README.md
- ansible/pulumi-env/roles/pulumi-env/defaults/main.yml
- ansible/pulumi-env/roles/pulumi-env/tasks/main.yml
- ansible/pulumi-env/roles/pulumi-env/vars/main.yml
This PR adds an Ansible role that will simplify creating a working Pulumi environment in a VM or a cloud instance.
> Add Ansible role to create Pulumi environment

- pulumi/aws-k8s-infra/README.md
- pulumi/aws-k8s-infra/index.ts
This PR adds an example of how to use Pulumi with TypeScript to create AWS infrastructure for use by Kubernetes.
> Add example of creating AWS infrastructure for Kubernetes

- kubernetes/capi-velero/README.md
- kubernetes/capi-velero/infra.tf
- kubernetes/capi-velero/instances.tf
- kubernetes/capi-velero/kubeadm-cp-mgmt-a.yaml
- kubernetes/capi-velero/kubeadm-cp-mgmt-b.yaml
- kubernetes/capi-velero/kubeadm-wkr-mgmt-a.yaml
- kubernetes/capi-velero/kubeadm-wkr-mgmt-b.yaml
- kubernetes/capi-velero/output.tf
- kubernetes/capi-velero/provider.tf
- kubernetes/capi-velero/securitygroups.tf
- kubernetes/capi-velero/terraform.tfvars.example
- kubernetes/capi-velero/variables.tf
This PR adds files for standing up infrastructure that can be used for CAPI-Velero testing. Specifically:
* A Terraform configuration for instantiating infrastructure on AWS;
* `kubeadm` configuration files for bootstrapping clusters using that infrastructure; and
* A `README.md` file that contains instructions for using these files.
These clusters can then be initialized as Cluster API management clusters using `clusterctl init`, and then used for testing Velero for backing up and restoring CAPI objects.
> Add files for standing up infrastructure for CAPI-Velero testing

- terraform/aws/new-beanstalk/main.tf
- terraform/aws/new-beanstalk/outputs.tf
- terraform/aws/new-beanstalk/readme.md
- terraform/aws/new-beanstalk/variables.tf
- terraform/aws/new-elasticache/main.tf
- terraform/aws/new-elasticache/output.tf
- terraform/aws/new-elasticache/readme.md
- terraform/aws/new-elasticache/variables.tf
- terraform/aws/new-igw/main.tf
- terraform/aws/new-igw/output.tf
- terraform/aws/new-igw/readme.md
- terraform/aws/new-igw/variables.tf
- terraform/aws/new-natgw/main.tf
- terraform/aws/new-natgw/output.tf
- terraform/aws/new-natgw/readme.md
- terraform/aws/new-natgw/variables.tf
- terraform/aws/new-s3/main.tf
- terraform/aws/new-s3/output.tf
- terraform/aws/new-s3/readme.md
- terraform/aws/new-s3/variables.tf
Hey @scottslowe 
As we discussed in https://github.com/scottslowe/learning-tools/issues/137 submitting PR with following new AWS resources: 
```
1. Internet Gateway
2. NAT Gateway
3. S3
4. Elasticache (memcached + redis clusters)
5. BeanStalk (application + environment)
```
Let me know if any corrections :)
> [Enhancement] Added new AWS resources for Terraform learning tool

- pulumi/default-aws-infra/README.md
- pulumi/default-aws-infra/main.go
This PR adds some Go-based code to show how to use Pulumi to launch an EC2 instance in/on the "default" AWS infrastructure created for every user (the default VPC, subnets, and Internet gateway).
> Add Pulumi example for using default AWS infrastructure

- debian/debian-pulumi-aws/Pulumi.yaml
- debian/debian-pulumi-aws/README.md
- debian/debian-pulumi-aws/go.mod
- debian/debian-pulumi-aws/main.go
This PR adds a Pulumi program (written in Go) that deploys a Debian-based EC2 instance. The program creates a dedicated VPC with only public subnets, and supports deploying either AMD64- or ARM64-based instances. The program also supports deploying an instance with Debian 10 ("Buster"), Debian 11 ("Bullseye"), or Debian 12 ("Bookworm") via configuration values.
> Add a Pulumi program to deploy a Debian-based EC2 instance

- debian/debian-pulumi-aws/go.mod
- debian/debian-pulumi-aws/main.go
- flatcar/flatcar-pulumi-aws/go.mod
- flatcar/flatcar-pulumi-aws/main.go
- ubuntu/ubuntu-pulumi-aws/main.go
This PR contains minor SSH key-related fixes and additions:
* Add SSH key to Flatcar and Debian programs.
* Remove references to keypair name.
* Use `pulumi.BoolRef` in AMI lookup.
* Minor code cleanup.
Closes both #150 and #151.
> Minor SSH key fixes

- pulumi/eks-from-scratch/main.go
This PR fixes the addons by explicitly declaring all the necessary addons in code. Previously, if not explicitly declared, they were installed but were not manageable as addons. This PR corrects that behavior.
> Fix EKS addons
